version: "3"

volumes:
  mongodata:

services:
  mongodb:
    image: mongo:3.4

  webapi:
    build: 
      context: ./BookLibrary
      dockerfile: Dockerfile
    image: booklibrary-netcore
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=mongodb://mongodb/library_database
    depends_on:
      - mongodb
