version: '2.1'
services:
  booklibrary-netcore-build:
    image: microsoft/aspnetcore-build:1.1
    volumes:
      - .:/sln
    working_dir: /sln
    entrypoint: ["bash", "./build.sh", "BookLibrary/BookLibrary.csproj"]