version: '3'
services:
  booklibrary:
    build: ./publish
    image: booklibrary-netcore
    container_name: booklibrary
    environment:
      ConnectionStrings__DefaultConnection: "mongodb://<MONGOHOST>/library_database"
    ports:
      - "8080:80"
